# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zEYNTIn5V3ZK3KwdO3ugJ3r5YDCcngsz

## Internship Assignment  for NLP
"""

!pip install --quiet git+https://github.com/huggingface/transformers.git@5c00918681d6b4027701eb46cea8f795da0d4064
!pip install --quiet sentencepiece==0.1.95

!pip install transformers

from transformers import T5ForConditionalGeneration,T5Tokenizer

#T5 model size on disk ~ 900 MB
question_model = T5ForConditionalGeneration.from_pretrained('ramsrigouthamg/t5_squad_v1')
question_tokenizer = T5Tokenizer.from_pretrained('ramsrigouthamg/t5_squad_v1')

def get_question(sentence,answer,mdl,tknizer):
  text = "context: {} answer: {}".format(sentence,answer)
  max_len = 256
  encoding = tknizer.encode_plus(text,max_length=max_len, pad_to_max_length=False,truncation=True, return_tensors="pt")

  input_ids, attention_mask = encoding["input_ids"], encoding["attention_mask"]

  outs = mdl.generate(input_ids=input_ids,
                                  attention_mask=attention_mask,
                                  early_stopping=True,
                                  num_beams=5,
                                  num_return_sequences=1,
                                  no_repeat_ngram_size=2,
                                  max_length=300)


  dec = [tknizer.decode(ids,skip_special_tokens=True) for ids in outs]


  Question = dec[0].replace("question:","")
  Question= Question.strip()
  return Question


context = '''In many regions, tribal groups lived by hunting
animals and gathering forest produce. They saw forests
as essential for survival. The Khonds were such a
community living in the forests of Orissa. They regularly
went out on collective hunts and then divided the meat
a m o n g s t t h e m s e l v e s .
They ate fruits and roots
collected from the forest
and cooked food with the
oil they extracted from
the seeds of the sal and
mahua. They used many
forest shrubs and herbs
for medicinal purposes,
and sold forest produce
in the local markets. The
local weavers and leather
workers tur ned to the
Khonds when they needed
supplies of kusum and
palash flowers to colour
their clothes and leather'''

input_string = input("Enter the answers (separated by spaces): ")
user_list = input_string.split()
a=len(user_list)
for i in range (0,a):
 answer = user_list[i]

 ques = get_question(context,answer,question_model,question_tokenizer)
 print (i+1,") Question: ",ques)
 print ("Answer: ",answer)
 i=i+1